export const USER_ROLE = {
  super_admin: "super_admin",
  admin: "admin",
  hr: "hr",
  accounts: "accounts",
  manager: "manager",
  employee: "employee",
} as const;

export type TUserRole = (typeof USER_ROLE)[keyof typeof USER_ROLE];

export const USER_ROLES = Object.values(USER_ROLE);

export const PERMISSIONS = {
  USER_READ: "user:read",
  USER_MANAGE: "user:manage",

  COMPANY_READ: "company:read",
  COMPANY_MANAGE: "company:manage",

  MAJOR_DEPARTMENT_READ: "major_department:read",
  MAJOR_DEPARTMENT_MANAGE: "major_department:manage",

  DESIGNATION_READ: "designation:read",
  DESIGNATION_MANAGE: "designation:manage",

  BRANCH_READ: "branch:read",
  BRANCH_MANAGE: "branch:manage",

  DEPARTMENT_READ: "department:read",
  DEPARTMENT_MANAGE: "department:manage",

  EMPLOYEE_READ: "employee:read",
  EMPLOYEE_MANAGE: "employee:manage",

  EMPLOYEE_BANK_INFO_READ: "employee_bank_info:read",
  EMPLOYEE_BANK_INFO_MANAGE: "employee_bank_info:manage",

  COMPANY_BANK_ACCOUNT_READ: "company_bank_account:read",
  COMPANY_BANK_ACCOUNT_MANAGE: "company_bank_account:manage",

  BANK_SHEET_READ: "bank_sheet:read",
  BANK_SHEET_MANAGE: "bank_sheet:manage",
  BANK_SHEET_EXPORT: "bank_sheet:export",

  ATTENDANCE_READ: "attendance:read",
  ATTENDANCE_MANAGE: "attendance:manage",

  ATTENDANCE_FINALIZATION_READ: "attendance_finalization:read",
  ATTENDANCE_FINALIZATION_PROCESS: "attendance_finalization:process",
  ATTENDANCE_FINALIZATION_APPROVE: "attendance_finalization:approve",
  ATTENDANCE_FINALIZATION_LOCK: "attendance_finalization:lock",
  ATTENDANCE_FINALIZATION_UNLOCK: "attendance_finalization:unlock",

  LEAVE_READ: "leave:read",
  LEAVE_MANAGE: "leave:manage",
  LEAVE_APPROVE: "leave:approve",

  HOLIDAY_READ: "holiday:read",
  HOLIDAY_MANAGE: "holiday:manage",

  SALARY_STRUCTURE_READ: "salary_structure:read",
  SALARY_STRUCTURE_MANAGE: "salary_structure:manage",

  PAYROLL_READ: "payroll:read",
  PAYROLL_UPDATE: "payroll:update",
  PAYROLL_PROCESS: "payroll:process",
  PAYROLL_APPROVE: "payroll:approve",
  PAYROLL_PAY: "payroll:pay",
  PAYROLL_LOCK: "payroll:lock",
  PAYROLL_UNLOCK: "payroll:unlock",
  PAYROLL_BATCH_APPROVE: "payroll:batch_approve",
  PAYROLL_BATCH_LOCK: "payroll:batch_lock",
  PAYROLL_AUDIT_READ: "payroll:audit_read",

  PAYROLL_REPORT_READ: "payroll_report:read",
  PAYROLL_REPORT_EXPORT: "payroll_report:export",

  TIME_BILL_READ: "time_bill:read",
  TIME_BILL_PROCESS: "time_bill:process",
  TIME_BILL_APPROVE: "time_bill:approve",
  TIME_BILL_LOCK: "time_bill:lock",
  TIME_BILL_UNLOCK: "time_bill:unlock",
  TIME_BILL_EXPORT: "time_bill:export",

  OT_STATEMENT_READ: "ot_statement:read",
  OT_STATEMENT_PROCESS: "ot_statement:process",
  OT_STATEMENT_APPROVE: "ot_statement:approve",
  OT_STATEMENT_LOCK: "ot_statement:lock",
  OT_STATEMENT_UNLOCK: "ot_statement:unlock",
  OT_STATEMENT_EXPORT: "ot_statement:export",

  OT_PAYMENT_DISTRIBUTION_READ: "ot_payment_distribution:read",
  OT_PAYMENT_DISTRIBUTION_PROCESS: "ot_payment_distribution:process",
  OT_PAYMENT_DISTRIBUTION_APPROVE: "ot_payment_distribution:approve",
  OT_PAYMENT_DISTRIBUTION_LOCK: "ot_payment_distribution:lock",
  OT_PAYMENT_DISTRIBUTION_UNLOCK: "ot_payment_distribution:unlock",
  OT_PAYMENT_DISTRIBUTION_EXPORT: "ot_payment_distribution:export",

  PAYSLIP_READ_ANY: "payslip:read:any",
  PAYSLIP_READ_OWN: "payslip:read:own",

  AUDIT_LOG_READ: "audit_log:read",
} as const;

export type TPermission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LIST = Object.values(PERMISSIONS) as TPermission[];

const ALL_PERMISSIONS: TPermission[] = [...PERMISSION_LIST];

export const ROLE_PERMISSIONS: Record<TUserRole, TPermission[]> = {
  [USER_ROLE.super_admin]: ALL_PERMISSIONS,
  [USER_ROLE.admin]: ALL_PERMISSIONS,

  [USER_ROLE.hr]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.COMPANY_MANAGE,

    PERMISSIONS.MAJOR_DEPARTMENT_READ,
    PERMISSIONS.MAJOR_DEPARTMENT_MANAGE,

    PERMISSIONS.DESIGNATION_READ,
    PERMISSIONS.DESIGNATION_MANAGE,

    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.BRANCH_MANAGE,

    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_MANAGE,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_MANAGE,

    PERMISSIONS.EMPLOYEE_BANK_INFO_READ,
    PERMISSIONS.EMPLOYEE_BANK_INFO_MANAGE,

    PERMISSIONS.COMPANY_BANK_ACCOUNT_READ,
    PERMISSIONS.COMPANY_BANK_ACCOUNT_MANAGE,

    PERMISSIONS.BANK_SHEET_READ,
    PERMISSIONS.BANK_SHEET_MANAGE,
    PERMISSIONS.BANK_SHEET_EXPORT,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.ATTENDANCE_FINALIZATION_READ,
    PERMISSIONS.ATTENDANCE_FINALIZATION_PROCESS,
    PERMISSIONS.ATTENDANCE_FINALIZATION_APPROVE,
    PERMISSIONS.ATTENDANCE_FINALIZATION_LOCK,
    PERMISSIONS.ATTENDANCE_FINALIZATION_UNLOCK,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.LEAVE_APPROVE,

    PERMISSIONS.HOLIDAY_READ,
    PERMISSIONS.HOLIDAY_MANAGE,

    PERMISSIONS.SALARY_STRUCTURE_READ,
    PERMISSIONS.SALARY_STRUCTURE_MANAGE,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_UPDATE,
    PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.PAYROLL_AUDIT_READ,

    PERMISSIONS.PAYROLL_REPORT_READ,
    PERMISSIONS.PAYROLL_REPORT_EXPORT,

    PERMISSIONS.TIME_BILL_READ,
    PERMISSIONS.TIME_BILL_PROCESS,
    PERMISSIONS.TIME_BILL_APPROVE,
    PERMISSIONS.TIME_BILL_LOCK,
    PERMISSIONS.TIME_BILL_UNLOCK,
    PERMISSIONS.TIME_BILL_EXPORT,

    PERMISSIONS.OT_STATEMENT_READ,
    PERMISSIONS.OT_STATEMENT_PROCESS,
    PERMISSIONS.OT_STATEMENT_APPROVE,
    PERMISSIONS.OT_STATEMENT_LOCK,
    PERMISSIONS.OT_STATEMENT_UNLOCK,
    PERMISSIONS.OT_STATEMENT_EXPORT,

    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_PROCESS,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_LOCK,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_UNLOCK,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_EXPORT,

    PERMISSIONS.PAYSLIP_READ_ANY,
  ],

  [USER_ROLE.accounts]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.COMPANY_READ,

    PERMISSIONS.MAJOR_DEPARTMENT_READ,

    PERMISSIONS.DESIGNATION_READ,

    PERMISSIONS.BRANCH_READ,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.EMPLOYEE_READ,

    PERMISSIONS.EMPLOYEE_BANK_INFO_READ,
    PERMISSIONS.EMPLOYEE_BANK_INFO_MANAGE,

    PERMISSIONS.COMPANY_BANK_ACCOUNT_READ,
    PERMISSIONS.COMPANY_BANK_ACCOUNT_MANAGE,

    PERMISSIONS.BANK_SHEET_READ,
    PERMISSIONS.BANK_SHEET_MANAGE,
    PERMISSIONS.BANK_SHEET_EXPORT,

    PERMISSIONS.ATTENDANCE_FINALIZATION_READ,

    PERMISSIONS.HOLIDAY_READ,

    PERMISSIONS.SALARY_STRUCTURE_READ,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_PAY,
    PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.PAYROLL_AUDIT_READ,

    PERMISSIONS.PAYROLL_REPORT_READ,
    PERMISSIONS.PAYROLL_REPORT_EXPORT,

    PERMISSIONS.TIME_BILL_READ,
    PERMISSIONS.TIME_BILL_PROCESS,
    PERMISSIONS.TIME_BILL_APPROVE,
    PERMISSIONS.TIME_BILL_LOCK,
    PERMISSIONS.TIME_BILL_EXPORT,

    PERMISSIONS.OT_STATEMENT_READ,
    PERMISSIONS.OT_STATEMENT_PROCESS,
    PERMISSIONS.OT_STATEMENT_APPROVE,
    PERMISSIONS.OT_STATEMENT_LOCK,
    PERMISSIONS.OT_STATEMENT_EXPORT,

    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_PROCESS,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_LOCK,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_EXPORT,

    PERMISSIONS.PAYSLIP_READ_ANY,
  ],

  [USER_ROLE.manager]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.COMPANY_READ,

    PERMISSIONS.MAJOR_DEPARTMENT_READ,

    PERMISSIONS.DESIGNATION_READ,

    PERMISSIONS.BRANCH_READ,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.EMPLOYEE_READ,

    PERMISSIONS.ATTENDANCE_READ,

    PERMISSIONS.ATTENDANCE_FINALIZATION_READ,
    PERMISSIONS.ATTENDANCE_FINALIZATION_APPROVE,
    PERMISSIONS.ATTENDANCE_FINALIZATION_LOCK,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_APPROVE,

    PERMISSIONS.HOLIDAY_READ,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.PAYROLL_BATCH_APPROVE,
    PERMISSIONS.PAYROLL_BATCH_LOCK,
    PERMISSIONS.PAYROLL_AUDIT_READ,

    PERMISSIONS.PAYROLL_REPORT_READ,

    PERMISSIONS.TIME_BILL_READ,
    PERMISSIONS.TIME_BILL_APPROVE,
    PERMISSIONS.TIME_BILL_LOCK,

    PERMISSIONS.OT_STATEMENT_READ,
    PERMISSIONS.OT_STATEMENT_APPROVE,
    PERMISSIONS.OT_STATEMENT_LOCK,

    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_LOCK,

    PERMISSIONS.BANK_SHEET_READ,

    PERMISSIONS.PAYSLIP_READ_ANY,
  ],

  [USER_ROLE.employee]: [
    PERMISSIONS.COMPANY_READ,

    PERMISSIONS.MAJOR_DEPARTMENT_READ,

    PERMISSIONS.DESIGNATION_READ,

    PERMISSIONS.BRANCH_READ,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.HOLIDAY_READ,

    PERMISSIONS.PAYSLIP_READ_OWN,
  ],
};

export const hasPermission = (
  role: TUserRole | string | undefined,
  requiredPermissions: TPermission[],
) => {
  if (!role) {
    return false;
  }

  const permissions = ROLE_PERMISSIONS[role as TUserRole];

  if (!permissions) {
    return false;
  }

  return requiredPermissions.every((permission) =>
    permissions.includes(permission),
  );
};
