export const USER_ROLE = {
  super_admin: "super_admin",
  admin: "admin",
  hr: "hr",
  accounts: "accounts",
  manager: "manager",
  employee: "employee",
} as const;

export type TUserRole = (typeof USER_ROLE)[keyof typeof USER_ROLE];

export const USER_ROLES = Object.values(USER_ROLE);

export const PERMISSIONS = {
  USER_READ: "user:read",
  USER_MANAGE: "user:manage",

  COMPANY_READ: "company:read",
  COMPANY_MANAGE: "company:manage",

  MAJOR_DEPARTMENT_READ: "major_department:read",
  MAJOR_DEPARTMENT_MANAGE: "major_department:manage",

  DESIGNATION_READ: "designation:read",
  DESIGNATION_MANAGE: "designation:manage",

  BRANCH_READ: "branch:read",
  BRANCH_MANAGE: "branch:manage",

  DEPARTMENT_READ: "department:read",
  DEPARTMENT_MANAGE: "department:manage",

  EMPLOYEE_READ: "employee:read",
  EMPLOYEE_MANAGE: "employee:manage",

  EMPLOYEE_BULK_IMPORT_READ: "employee_bulk_import:read",
  EMPLOYEE_BULK_IMPORT_PROCESS: "employee_bulk_import:process",
  EMPLOYEE_BULK_IMPORT_EXPORT: "employee_bulk_import:export",
  EMPLOYEE_BULK_IMPORT_REVERT: "employee_bulk_import:revert",

  EMPLOYEE_MOVEMENT_READ: "employee_movement:read",
  EMPLOYEE_MOVEMENT_MANAGE: "employee_movement:manage",
  EMPLOYEE_MOVEMENT_APPROVE: "employee_movement:approve",
  EMPLOYEE_MOVEMENT_APPLY: "employee_movement:apply",
  EMPLOYEE_MOVEMENT_PAYROLL_IMPACT_READ:
    "employee_movement:payroll_impact_read",

  EMPLOYEE_BANK_INFO_READ: "employee_bank_info:read",
  EMPLOYEE_BANK_INFO_MANAGE: "employee_bank_info:manage",

  COMPANY_BANK_ACCOUNT_READ: "company_bank_account:read",
  COMPANY_BANK_ACCOUNT_MANAGE: "company_bank_account:manage",

  BANK_SHEET_READ: "bank_sheet:read",
  BANK_SHEET_MANAGE: "bank_sheet:manage",
  BANK_SHEET_EXPORT: "bank_sheet:export",

  ATTENDANCE_READ: "attendance:read",
  ATTENDANCE_MANAGE: "attendance:manage",

  ATTENDANCE_IMPORT_READ: "attendance_import:read",
  ATTENDANCE_IMPORT_PROCESS: "attendance_import:process",
  ATTENDANCE_IMPORT_EXPORT: "attendance_import:export",
  ATTENDANCE_IMPORT_REVERT: "attendance_import:revert",

  ATTENDANCE_FINALIZATION_READ: "attendance_finalization:read",
  ATTENDANCE_FINALIZATION_PROCESS: "attendance_finalization:process",
  ATTENDANCE_FINALIZATION_APPROVE: "attendance_finalization:approve",
  ATTENDANCE_FINALIZATION_LOCK: "attendance_finalization:lock",
  ATTENDANCE_FINALIZATION_UNLOCK: "attendance_finalization:unlock",

  LEAVE_READ: "leave:read",
  LEAVE_MANAGE: "leave:manage",
  LEAVE_APPROVE: "leave:approve",

  LEAVE_BALANCE_READ: "leave_balance:read",
  LEAVE_BALANCE_PROCESS: "leave_balance:process",
  LEAVE_BALANCE_ADJUST: "leave_balance:adjust",
  LEAVE_BALANCE_LOCK: "leave_balance:lock",
  LEAVE_BALANCE_UNLOCK: "leave_balance:unlock",
  LEAVE_BALANCE_EXPORT: "leave_balance:export",

  HOLIDAY_READ: "holiday:read",
  HOLIDAY_MANAGE: "holiday:manage",

  SALARY_STRUCTURE_READ: "salary_structure:read",
  SALARY_STRUCTURE_MANAGE: "salary_structure:manage",

  SALARY_SHEET_READ: "salary_sheet:read",
  SALARY_SHEET_PROCESS: "salary_sheet:process",
  SALARY_SHEET_APPROVE: "salary_sheet:approve",
  SALARY_SHEET_LOCK: "salary_sheet:lock",
  SALARY_SHEET_UNLOCK: "salary_sheet:unlock",

  SALARY_STATEMENT_READ: "salary_statement:read",
  SALARY_STATEMENT_PROCESS: "salary_statement:process",
  SALARY_STATEMENT_APPROVE: "salary_statement:approve",
  SALARY_STATEMENT_LOCK: "salary_statement:lock",
  SALARY_STATEMENT_UNLOCK: "salary_statement:unlock",

  SALARY_PAYMENT_DISTRIBUTION_READ: "salary_payment_distribution:read",
  SALARY_PAYMENT_DISTRIBUTION_PROCESS: "salary_payment_distribution:process",
  SALARY_PAYMENT_DISTRIBUTION_APPROVE: "salary_payment_distribution:approve",
  SALARY_PAYMENT_DISTRIBUTION_LOCK: "salary_payment_distribution:lock",
  SALARY_PAYMENT_DISTRIBUTION_UNLOCK: "salary_payment_distribution:unlock",
  SALARY_PAYMENT_DISTRIBUTION_EXPORT: "salary_payment_distribution:export",

  PAYROLL_READ: "payroll:read",
  PAYROLL_UPDATE: "payroll:update",
  PAYROLL_PROCESS: "payroll:process",
  PAYROLL_APPROVE: "payroll:approve",
  PAYROLL_PAY: "payroll:pay",
  PAYROLL_LOCK: "payroll:lock",
  PAYROLL_UNLOCK: "payroll:unlock",
  PAYROLL_BATCH_APPROVE: "payroll:batch_approve",
  PAYROLL_BATCH_LOCK: "payroll:batch_lock",
  PAYROLL_AUDIT_READ: "payroll:audit_read",

  PAYROLL_REPORT_READ: "payroll_report:read",
  PAYROLL_REPORT_EXPORT: "payroll_report:export",

  REPORT_CENTER_READ: "report_center:read",

  TIME_BILL_READ: "time_bill:read",
  TIME_BILL_PROCESS: "time_bill:process",
  TIME_BILL_APPROVE: "time_bill:approve",
  TIME_BILL_LOCK: "time_bill:lock",
  TIME_BILL_UNLOCK: "time_bill:unlock",
  TIME_BILL_EXPORT: "time_bill:export",

  OT_STATEMENT_READ: "ot_statement:read",
  OT_STATEMENT_PROCESS: "ot_statement:process",
  OT_STATEMENT_APPROVE: "ot_statement:approve",
  OT_STATEMENT_LOCK: "ot_statement:lock",
  OT_STATEMENT_UNLOCK: "ot_statement:unlock",
  OT_STATEMENT_EXPORT: "ot_statement:export",

  OT_PAYMENT_DISTRIBUTION_READ: "ot_payment_distribution:read",
  OT_PAYMENT_DISTRIBUTION_PROCESS: "ot_payment_distribution:process",
  OT_PAYMENT_DISTRIBUTION_APPROVE: "ot_payment_distribution:approve",
  OT_PAYMENT_DISTRIBUTION_LOCK: "ot_payment_distribution:lock",
  OT_PAYMENT_DISTRIBUTION_UNLOCK: "ot_payment_distribution:unlock",
  OT_PAYMENT_DISTRIBUTION_EXPORT: "ot_payment_distribution:export",

  PAYSLIP_READ_ANY: "payslip:read:any",
  PAYSLIP_READ_OWN: "payslip:read:own",

  MONTH_END_PROCESS_CONTROL_READ: "month_end_process_control:read",

  BONUS_SHEET_READ: "bonus_sheet:read",
  BONUS_SHEET_PROCESS: "bonus_sheet:process",
  BONUS_SHEET_APPROVE: "bonus_sheet:approve",
  BONUS_SHEET_LOCK: "bonus_sheet:lock",
  BONUS_SHEET_UNLOCK: "bonus_sheet:unlock",

  BONUS_STATEMENT_READ: "bonus_statement:read",
  BONUS_STATEMENT_PROCESS: "bonus_statement:process",
  BONUS_STATEMENT_APPROVE: "bonus_statement:approve",
  BONUS_STATEMENT_LOCK: "bonus_statement:lock",
  BONUS_STATEMENT_UNLOCK: "bonus_statement:unlock",

  BONUS_PAYMENT_DISTRIBUTION_READ: "bonus_payment_distribution:read",
  BONUS_PAYMENT_DISTRIBUTION_PROCESS: "bonus_payment_distribution:process",
  BONUS_PAYMENT_DISTRIBUTION_APPROVE: "bonus_payment_distribution:approve",
  BONUS_PAYMENT_DISTRIBUTION_LOCK: "bonus_payment_distribution:lock",
  BONUS_PAYMENT_DISTRIBUTION_UNLOCK: "bonus_payment_distribution:unlock",
  BONUS_PAYMENT_DISTRIBUTION_EXPORT: "bonus_payment_distribution:export",

  AUDIT_LOG_READ: "audit_log:read",
} as const;

export type TPermission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LIST = Object.values(PERMISSIONS) as TPermission[];

const ALL_PERMISSIONS: TPermission[] = [...PERMISSION_LIST];

export const ROLE_PERMISSIONS: Record<TUserRole, TPermission[]> = {
  [USER_ROLE.super_admin]: ALL_PERMISSIONS,
  [USER_ROLE.admin]: ALL_PERMISSIONS,

  [USER_ROLE.hr]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.COMPANY_MANAGE,

    PERMISSIONS.MAJOR_DEPARTMENT_READ,
    PERMISSIONS.MAJOR_DEPARTMENT_MANAGE,

    PERMISSIONS.DESIGNATION_READ,
    PERMISSIONS.DESIGNATION_MANAGE,

    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.BRANCH_MANAGE,

    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_MANAGE,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_MANAGE,
    PERMISSIONS.EMPLOYEE_BULK_IMPORT_READ,
    PERMISSIONS.EMPLOYEE_BULK_IMPORT_PROCESS,
    PERMISSIONS.EMPLOYEE_BULK_IMPORT_EXPORT,
    PERMISSIONS.EMPLOYEE_BULK_IMPORT_REVERT,
    PERMISSIONS.EMPLOYEE_MOVEMENT_READ,
    PERMISSIONS.EMPLOYEE_MOVEMENT_MANAGE,
    PERMISSIONS.EMPLOYEE_MOVEMENT_APPROVE,
    PERMISSIONS.EMPLOYEE_MOVEMENT_APPLY,
    PERMISSIONS.EMPLOYEE_MOVEMENT_PAYROLL_IMPACT_READ,

    PERMISSIONS.EMPLOYEE_BANK_INFO_READ,
    PERMISSIONS.EMPLOYEE_BANK_INFO_MANAGE,

    PERMISSIONS.COMPANY_BANK_ACCOUNT_READ,
    PERMISSIONS.COMPANY_BANK_ACCOUNT_MANAGE,

    PERMISSIONS.BANK_SHEET_READ,
    PERMISSIONS.BANK_SHEET_MANAGE,
    PERMISSIONS.BANK_SHEET_EXPORT,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.ATTENDANCE_IMPORT_READ,
    PERMISSIONS.ATTENDANCE_IMPORT_PROCESS,
    PERMISSIONS.ATTENDANCE_IMPORT_EXPORT,
    PERMISSIONS.ATTENDANCE_IMPORT_REVERT,

    PERMISSIONS.ATTENDANCE_FINALIZATION_READ,
    PERMISSIONS.ATTENDANCE_FINALIZATION_PROCESS,
    PERMISSIONS.ATTENDANCE_FINALIZATION_APPROVE,
    PERMISSIONS.ATTENDANCE_FINALIZATION_LOCK,
    PERMISSIONS.ATTENDANCE_FINALIZATION_UNLOCK,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.LEAVE_APPROVE,

    PERMISSIONS.LEAVE_BALANCE_READ,
    PERMISSIONS.LEAVE_BALANCE_PROCESS,
    PERMISSIONS.LEAVE_BALANCE_ADJUST,
    PERMISSIONS.LEAVE_BALANCE_LOCK,
    PERMISSIONS.LEAVE_BALANCE_UNLOCK,
    PERMISSIONS.LEAVE_BALANCE_EXPORT,

    PERMISSIONS.HOLIDAY_READ,
    PERMISSIONS.HOLIDAY_MANAGE,

    PERMISSIONS.SALARY_STRUCTURE_READ,
    PERMISSIONS.SALARY_STRUCTURE_MANAGE,

    PERMISSIONS.SALARY_SHEET_READ,
    PERMISSIONS.SALARY_SHEET_PROCESS,
    PERMISSIONS.SALARY_SHEET_APPROVE,
    PERMISSIONS.SALARY_SHEET_LOCK,
    PERMISSIONS.SALARY_SHEET_UNLOCK,

    PERMISSIONS.SALARY_STATEMENT_READ,
    PERMISSIONS.SALARY_STATEMENT_PROCESS,
    PERMISSIONS.SALARY_STATEMENT_APPROVE,
    PERMISSIONS.SALARY_STATEMENT_LOCK,
    PERMISSIONS.SALARY_STATEMENT_UNLOCK,

    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_PROCESS,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_LOCK,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_UNLOCK,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_EXPORT,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_UPDATE,
    PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.PAYROLL_AUDIT_READ,

    PERMISSIONS.PAYROLL_REPORT_READ,
    PERMISSIONS.PAYROLL_REPORT_EXPORT,

    PERMISSIONS.REPORT_CENTER_READ,

    PERMISSIONS.TIME_BILL_READ,
    PERMISSIONS.TIME_BILL_PROCESS,
    PERMISSIONS.TIME_BILL_APPROVE,
    PERMISSIONS.TIME_BILL_LOCK,
    PERMISSIONS.TIME_BILL_UNLOCK,
    PERMISSIONS.TIME_BILL_EXPORT,

    PERMISSIONS.OT_STATEMENT_READ,
    PERMISSIONS.OT_STATEMENT_PROCESS,
    PERMISSIONS.OT_STATEMENT_APPROVE,
    PERMISSIONS.OT_STATEMENT_LOCK,
    PERMISSIONS.OT_STATEMENT_UNLOCK,
    PERMISSIONS.OT_STATEMENT_EXPORT,

    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_PROCESS,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_LOCK,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_UNLOCK,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_EXPORT,

    PERMISSIONS.MONTH_END_PROCESS_CONTROL_READ,

    PERMISSIONS.BONUS_SHEET_READ,
    PERMISSIONS.BONUS_SHEET_PROCESS,
    PERMISSIONS.BONUS_SHEET_APPROVE,
    PERMISSIONS.BONUS_SHEET_LOCK,
    PERMISSIONS.BONUS_SHEET_UNLOCK,

    PERMISSIONS.BONUS_STATEMENT_READ,
    PERMISSIONS.BONUS_STATEMENT_PROCESS,
    PERMISSIONS.BONUS_STATEMENT_APPROVE,
    PERMISSIONS.BONUS_STATEMENT_LOCK,
    PERMISSIONS.BONUS_STATEMENT_UNLOCK,

    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_PROCESS,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_LOCK,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_UNLOCK,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_EXPORT,

    PERMISSIONS.PAYSLIP_READ_ANY,
  ],

  [USER_ROLE.accounts]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.COMPANY_READ,

    PERMISSIONS.MAJOR_DEPARTMENT_READ,

    PERMISSIONS.DESIGNATION_READ,

    PERMISSIONS.BRANCH_READ,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_BULK_IMPORT_READ,
    PERMISSIONS.EMPLOYEE_BULK_IMPORT_EXPORT,
    PERMISSIONS.EMPLOYEE_MOVEMENT_READ,
    PERMISSIONS.EMPLOYEE_MOVEMENT_PAYROLL_IMPACT_READ,

    PERMISSIONS.EMPLOYEE_BANK_INFO_READ,
    PERMISSIONS.EMPLOYEE_BANK_INFO_MANAGE,

    PERMISSIONS.COMPANY_BANK_ACCOUNT_READ,
    PERMISSIONS.COMPANY_BANK_ACCOUNT_MANAGE,

    PERMISSIONS.BANK_SHEET_READ,
    PERMISSIONS.BANK_SHEET_MANAGE,
    PERMISSIONS.BANK_SHEET_EXPORT,

    PERMISSIONS.ATTENDANCE_IMPORT_READ,
    PERMISSIONS.ATTENDANCE_IMPORT_EXPORT,

    PERMISSIONS.ATTENDANCE_FINALIZATION_READ,

    PERMISSIONS.HOLIDAY_READ,

    PERMISSIONS.LEAVE_BALANCE_READ,
    PERMISSIONS.LEAVE_BALANCE_EXPORT,

    PERMISSIONS.SALARY_STRUCTURE_READ,

    PERMISSIONS.SALARY_SHEET_READ,
    PERMISSIONS.SALARY_SHEET_PROCESS,
    PERMISSIONS.SALARY_SHEET_APPROVE,
    PERMISSIONS.SALARY_SHEET_LOCK,

    PERMISSIONS.SALARY_STATEMENT_READ,
    PERMISSIONS.SALARY_STATEMENT_PROCESS,
    PERMISSIONS.SALARY_STATEMENT_APPROVE,
    PERMISSIONS.SALARY_STATEMENT_LOCK,

    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_PROCESS,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_LOCK,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_EXPORT,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_PAY,
    PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.PAYROLL_AUDIT_READ,

    PERMISSIONS.PAYROLL_REPORT_READ,
    PERMISSIONS.PAYROLL_REPORT_EXPORT,

    PERMISSIONS.REPORT_CENTER_READ,

    PERMISSIONS.TIME_BILL_READ,
    PERMISSIONS.TIME_BILL_PROCESS,
    PERMISSIONS.TIME_BILL_APPROVE,
    PERMISSIONS.TIME_BILL_LOCK,
    PERMISSIONS.TIME_BILL_EXPORT,

    PERMISSIONS.OT_STATEMENT_READ,
    PERMISSIONS.OT_STATEMENT_PROCESS,
    PERMISSIONS.OT_STATEMENT_APPROVE,
    PERMISSIONS.OT_STATEMENT_LOCK,
    PERMISSIONS.OT_STATEMENT_EXPORT,

    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_PROCESS,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_LOCK,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_EXPORT,

    PERMISSIONS.MONTH_END_PROCESS_CONTROL_READ,

    PERMISSIONS.BONUS_SHEET_READ,
    PERMISSIONS.BONUS_SHEET_PROCESS,
    PERMISSIONS.BONUS_SHEET_APPROVE,
    PERMISSIONS.BONUS_SHEET_LOCK,

    PERMISSIONS.BONUS_STATEMENT_READ,
    PERMISSIONS.BONUS_STATEMENT_PROCESS,
    PERMISSIONS.BONUS_STATEMENT_APPROVE,
    PERMISSIONS.BONUS_STATEMENT_LOCK,

    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_PROCESS,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_LOCK,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_EXPORT,

    PERMISSIONS.PAYSLIP_READ_ANY,
  ],

  [USER_ROLE.manager]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.COMPANY_READ,

    PERMISSIONS.MAJOR_DEPARTMENT_READ,

    PERMISSIONS.DESIGNATION_READ,

    PERMISSIONS.BRANCH_READ,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_BULK_IMPORT_READ,
    PERMISSIONS.EMPLOYEE_MOVEMENT_READ,
    PERMISSIONS.EMPLOYEE_MOVEMENT_APPROVE,
    PERMISSIONS.EMPLOYEE_MOVEMENT_PAYROLL_IMPACT_READ,

    PERMISSIONS.ATTENDANCE_READ,

    PERMISSIONS.ATTENDANCE_IMPORT_READ,
    PERMISSIONS.ATTENDANCE_IMPORT_EXPORT,

    PERMISSIONS.ATTENDANCE_FINALIZATION_READ,
    PERMISSIONS.ATTENDANCE_FINALIZATION_APPROVE,
    PERMISSIONS.ATTENDANCE_FINALIZATION_LOCK,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_APPROVE,

    PERMISSIONS.LEAVE_BALANCE_READ,
    PERMISSIONS.LEAVE_BALANCE_LOCK,
    PERMISSIONS.LEAVE_BALANCE_EXPORT,

    PERMISSIONS.HOLIDAY_READ,

    PERMISSIONS.SALARY_SHEET_READ,
    PERMISSIONS.SALARY_SHEET_APPROVE,
    PERMISSIONS.SALARY_SHEET_LOCK,

    PERMISSIONS.SALARY_STATEMENT_READ,
    PERMISSIONS.SALARY_STATEMENT_APPROVE,
    PERMISSIONS.SALARY_STATEMENT_LOCK,

    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_LOCK,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.PAYROLL_BATCH_APPROVE,
    PERMISSIONS.PAYROLL_BATCH_LOCK,
    PERMISSIONS.PAYROLL_AUDIT_READ,

    PERMISSIONS.PAYROLL_REPORT_READ,

    PERMISSIONS.REPORT_CENTER_READ,

    PERMISSIONS.TIME_BILL_READ,
    PERMISSIONS.TIME_BILL_APPROVE,
    PERMISSIONS.TIME_BILL_LOCK,

    PERMISSIONS.OT_STATEMENT_READ,
    PERMISSIONS.OT_STATEMENT_APPROVE,
    PERMISSIONS.OT_STATEMENT_LOCK,

    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.OT_PAYMENT_DISTRIBUTION_LOCK,

    PERMISSIONS.MONTH_END_PROCESS_CONTROL_READ,

    PERMISSIONS.BONUS_SHEET_READ,
    PERMISSIONS.BONUS_SHEET_APPROVE,
    PERMISSIONS.BONUS_SHEET_LOCK,

    PERMISSIONS.BONUS_STATEMENT_READ,
    PERMISSIONS.BONUS_STATEMENT_APPROVE,
    PERMISSIONS.BONUS_STATEMENT_LOCK,

    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_READ,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_APPROVE,
    PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_LOCK,

    PERMISSIONS.BANK_SHEET_READ,

    PERMISSIONS.PAYSLIP_READ_ANY,
  ],

  [USER_ROLE.employee]: [
    PERMISSIONS.COMPANY_READ,

    PERMISSIONS.MAJOR_DEPARTMENT_READ,

    PERMISSIONS.DESIGNATION_READ,

    PERMISSIONS.BRANCH_READ,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.HOLIDAY_READ,

    PERMISSIONS.PAYSLIP_READ_OWN,
  ],
};

export const hasPermission = (
  role: TUserRole | string | undefined,
  requiredPermissions: TPermission[],
) => {
  if (!role) {
    return false;
  }

  const permissions = ROLE_PERMISSIONS[role as TUserRole];

  if (!permissions) {
    return false;
  }

  return requiredPermissions.every((permission) =>
    permissions.includes(permission),
  );
};
