import PDFDocument from "pdfkit";
import { TBankSheetPreview, TBankSheetRow } from "./bankSheet.interface";
import { getMonthLabel } from "./bankSheet.utils";

const BANK_SHEET_PDF_MIME_TYPE = "application/pdf";
const COMPANY_NAME = "Chakda Steel & Re-Rolling Mills (Pvt.) Ltd.";
const SYSTEM_NAME = "CSRM Payroll System";

const sanitizeFileNamePart = (value: string) =>
  value
    .trim()
    .replace(/[^a-zA-Z0-9-_]/g, "-")
    .replace(/-+/g, "-");

const formatDate = (date = new Date()) =>
  date.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

const formatAmount = (amount: number) =>
  Number(amount || 0).toLocaleString("en-US", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  });

const numberToWordsBelowThousand = (amount: number): string => {
  const ones = [
    "",
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight",
    "Nine",
    "Ten",
    "Eleven",
    "Twelve",
    "Thirteen",
    "Fourteen",
    "Fifteen",
    "Sixteen",
    "Seventeen",
    "Eighteen",
    "Nineteen",
  ];

  const tens = [
    "",
    "",
    "Twenty",
    "Thirty",
    "Forty",
    "Fifty",
    "Sixty",
    "Seventy",
    "Eighty",
    "Ninety",
  ];

  if (amount === 0) return "";

  if (amount < 20) return ones[amount];

  if (amount < 100) {
    return `${tens[Math.floor(amount / 10)]} ${ones[amount % 10]}`.trim();
  }

  return `${ones[Math.floor(amount / 100)]} Hundred ${numberToWordsBelowThousand(
    amount % 100,
  )}`.trim();
};

const amountToWords = (amount: number) => {
  let remainingAmount = Math.round(Number(amount || 0));

  if (remainingAmount <= 0) {
    return "Zero Taka Only";
  }

  const crore = Math.floor(remainingAmount / 10000000);
  remainingAmount %= 10000000;

  const lakh = Math.floor(remainingAmount / 100000);
  remainingAmount %= 100000;

  const thousand = Math.floor(remainingAmount / 1000);
  remainingAmount %= 1000;

  const words: string[] = [];

  if (crore) words.push(`${numberToWordsBelowThousand(crore)} Crore`);
  if (lakh) words.push(`${numberToWordsBelowThousand(lakh)} Lakh`);
  if (thousand) words.push(`${numberToWordsBelowThousand(thousand)} Thousand`);
  if (remainingAmount) words.push(numberToWordsBelowThousand(remainingAmount));

  return `${words.join(" ")} Taka Only`;
};

const drawHorizontalLine = (doc: PDFKit.PDFDocument, y: number) => {
  doc
    .moveTo(doc.page.margins.left, y)
    .lineTo(doc.page.width - doc.page.margins.right, y)
    .stroke();
};

const addForwardingLetterPage = (
  doc: PDFKit.PDFDocument,
  preview: TBankSheetPreview,
) => {
  const monthLabel = getMonthLabel(preview.summary.month, preview.summary.year);
  const totalAmount = preview.summary.totalAmount;

  doc.fontSize(16).font("Helvetica-Bold").text(COMPANY_NAME, {
    align: "center",
  });

  doc.moveDown(0.3);
  doc.fontSize(10).font("Helvetica").text("Payroll & Accounts Department", {
    align: "center",
  });

  doc.moveDown(0.5);
  drawHorizontalLine(doc, doc.y);
  doc.moveDown(1.2);

  doc.fontSize(10).font("Helvetica").text(`Date: ${formatDate()}`, {
    align: "right",
  });

  doc.moveDown(1.2);
  doc.fontSize(11).font("Helvetica-Bold").text("To");
  doc.font("Helvetica").text("The Manager");
  doc.text("Concerned Bank Branch");
  doc.text("Bangladesh");

  doc.moveDown(1);
  doc
    .font("Helvetica-Bold")
    .text(
      "Subject: Request to process salary disbursement as per attached bank sheet.",
    );

  doc.moveDown(1);
  doc.font("Helvetica").text("Dear Sir/Madam,");

  doc.moveDown(0.8);
  doc.text(
    `With reference to the attached salary bank sheet for ${monthLabel}, you are requested to process salary disbursement to the listed employee bank accounts as per the account details and amounts mentioned in the annexure.`,
    { align: "justify", lineGap: 3 },
  );

  doc.moveDown(0.8);
  doc.text(
    `Total number of employees: ${preview.summary.totalIncluded}. Total amount: Tk. ${formatAmount(
      totalAmount,
    )} (${amountToWords(totalAmount)}).`,
    { align: "justify", lineGap: 3 },
  );

  doc.moveDown(0.8);
  doc.text(
    "Please debit the company salary disbursement account as per bank instruction and credit the respective employee accounts accordingly.",
    { align: "justify", lineGap: 3 },
  );

  doc.moveDown(1.2);
  doc.text("Thank you for your cooperation.");

  doc.moveDown(1.5);
  doc.text("Sincerely,");
  doc.moveDown(2.5);

  doc.font("Helvetica-Bold").text("Authorized Signatory");
  doc.font("Helvetica").text("HR/Admin & Accounts Department");
  doc.text(COMPANY_NAME);

  doc.moveDown(2);
  doc.fontSize(9).text(`Generated by ${SYSTEM_NAME}`, {
    align: "center",
  });
};

const addSummaryPage = (
  doc: PDFKit.PDFDocument,
  preview: TBankSheetPreview,
) => {
  const monthLabel = getMonthLabel(preview.summary.month, preview.summary.year);

  doc.addPage({ size: "A4", margin: 40 });

  doc.fontSize(15).font("Helvetica-Bold").text("Salary Bank Sheet Summary", {
    align: "center",
  });

  doc.moveDown(1);
  doc.fontSize(11).font("Helvetica");

  const summaryRows = [
    ["Payroll Month", monthLabel],
    ["Payroll Month Code", preview.summary.payrollMonth],
    ["Payment Mode", preview.summary.paymentMode],
    ["Total Payroll Found", String(preview.summary.totalPayrollFound)],
    ["Total Included", String(preview.summary.totalIncluded)],
    ["Total Excluded", String(preview.summary.totalExcluded)],
    ["Total Amount", `Tk. ${formatAmount(preview.summary.totalAmount)}`],
    ["Amount in Words", amountToWords(preview.summary.totalAmount)],
  ];

  summaryRows.forEach(([label, value]) => {
    doc.font("Helvetica-Bold").text(`${label}: `, { continued: true });
    doc.font("Helvetica").text(value);
    doc.moveDown(0.4);
  });

  doc.moveDown(1.5);
  doc.font("Helvetica-Bold").text("Prepared By", 70, doc.y);
  doc.text("Checked By", 240, doc.y - 12);
  doc.text("Approved By", 410, doc.y - 12);

  doc.moveDown(3);
  doc.font("Helvetica").text("________________", 70, doc.y);
  doc.text("________________", 240, doc.y - 12);
  doc.text("________________", 410, doc.y - 12);
};

const getColumnSettings = () => [
  {
    title: "SL",
    width: 28,
    getValue: (row: TBankSheetRow) => String(row.slNo),
  },
  {
    title: "Name of A/C",
    width: 145,
    getValue: (row: TBankSheetRow) => row.nameOfAccount,
  },
  {
    title: "A/C Bank Branch Code",
    width: 95,
    getValue: (row: TBankSheetRow) => row.accountBankBranchCode,
  },
  {
    title: "A/C No",
    width: 105,
    getValue: (row: TBankSheetRow) => row.accountNo,
  },
  {
    title: "Process Bank Branch No",
    width: 105,
    getValue: (row: TBankSheetRow) => row.processBankBranchNo,
  },
  {
    title: "Branch",
    width: 125,
    getValue: (row: TBankSheetRow) => row.branch,
  },
  {
    title: "Amount in Tk",
    width: 82,
    getValue: (row: TBankSheetRow) => formatAmount(row.amountInTk),
  },
];

const drawTableHeader = (
  doc: PDFKit.PDFDocument,
  startX: number,
  y: number,
) => {
  const columns = getColumnSettings();
  let x = startX;

  doc.fontSize(8).font("Helvetica-Bold");

  columns.forEach((column) => {
    doc.rect(x, y, column.width, 26).stroke();
    doc.text(column.title, x + 3, y + 5, {
      width: column.width - 6,
      align: "center",
    });
    x += column.width;
  });
};

const drawTableRow = (
  doc: PDFKit.PDFDocument,
  row: TBankSheetRow,
  startX: number,
  y: number,
) => {
  const columns = getColumnSettings();
  let x = startX;

  doc.fontSize(7.5).font("Helvetica");

  columns.forEach((column, index) => {
    const isAmountColumn = index === columns.length - 1;
    const isSlColumn = index === 0;

    doc.rect(x, y, column.width, 24).stroke();
    doc.text(column.getValue(row), x + 3, y + 6, {
      width: column.width - 6,
      align: isAmountColumn ? "right" : isSlColumn ? "center" : "left",
      ellipsis: true,
    });
    x += column.width;
  });
};

const addBankSheetAnnexurePages = (
  doc: PDFKit.PDFDocument,
  preview: TBankSheetPreview,
) => {
  const monthLabel = getMonthLabel(preview.summary.month, preview.summary.year);
  const startX = 36;
  const tableStartY = 86;
  const rowHeight = 24;
  const footerY = 535;

  doc.addPage({ size: "A4", layout: "landscape", margin: 36 });

  doc.fontSize(14).font("Helvetica-Bold").text(COMPANY_NAME, {
    align: "center",
  });

  doc.moveDown(0.2);
  doc.fontSize(11).text(`Salary Bank Sheet Annexure - ${monthLabel}`, {
    align: "center",
  });

  let currentY = tableStartY;
  drawTableHeader(doc, startX, currentY);
  currentY += 26;

  preview.rows.forEach((row) => {
    if (currentY + rowHeight > footerY) {
      doc.addPage({ size: "A4", layout: "landscape", margin: 36 });
      doc
        .fontSize(12)
        .font("Helvetica-Bold")
        .text(`Salary Bank Sheet Annexure - ${monthLabel}`, {
          align: "center",
        });

      currentY = tableStartY;
      drawTableHeader(doc, startX, currentY);
      currentY += 26;
    }

    drawTableRow(doc, row, startX, currentY);
    currentY += rowHeight;
  });

  if (currentY + rowHeight > footerY) {
    doc.addPage({ size: "A4", layout: "landscape", margin: 36 });
    currentY = tableStartY;
  }

  const columns = getColumnSettings();
  const totalWidth = columns.reduce((sum, column) => sum + column.width, 0);
  const amountWidth = columns[columns.length - 1].width;

  doc.fontSize(8).font("Helvetica-Bold");

  doc.rect(startX, currentY, totalWidth - amountWidth, rowHeight).stroke();
  doc.text("Total", startX + 3, currentY + 7, {
    width: totalWidth - amountWidth - 6,
    align: "right",
  });

  doc
    .rect(startX + totalWidth - amountWidth, currentY, amountWidth, rowHeight)
    .stroke();

  doc.text(
    formatAmount(preview.summary.totalAmount),
    startX + totalWidth - amountWidth + 3,
    currentY + 7,
    {
      width: amountWidth - 6,
      align: "right",
    },
  );
};

const addExcludedRowsPage = (
  doc: PDFKit.PDFDocument,
  preview: TBankSheetPreview,
) => {
  if (!preview.excludedRows.length) {
    return;
  }

  doc.addPage({ size: "A4", margin: 40 });

  doc.fontSize(14).font("Helvetica-Bold").text("Excluded Payroll Rows", {
    align: "center",
  });

  doc.moveDown(1);
  doc.fontSize(9).font("Helvetica");

  preview.excludedRows.forEach((row, index) => {
    if (doc.y > 740) {
      doc.addPage({ size: "A4", margin: 40 });
    }

    doc
      .font("Helvetica-Bold")
      .text(
        `${index + 1}. ${row.employee?.employeeId || "N/A"} - ${
          row.employee?.employeeName || "N/A"
        }`,
      );

    doc
      .font("Helvetica")
      .text(
        `Payable Salary: Tk. ${formatAmount(row.payableSalary)} | Reason: ${
          row.reason
        }`,
      );

    doc.moveDown(0.5);
  });
};

export const generateSalaryBankSheetForwardingLetterPDF = async (
  preview: TBankSheetPreview,
) => {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => chunks.push(Buffer.from(chunk)));

  const pdfBufferPromise = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  addForwardingLetterPage(doc, preview);
  addSummaryPage(doc, preview);
  addBankSheetAnnexurePages(doc, preview);
  addExcludedRowsPage(doc, preview);

  doc.end();

  const buffer = await pdfBufferPromise;

  const fileName = `salary-bank-forwarding-letter-${sanitizeFileNamePart(
    preview.summary.payrollMonth,
  )}.pdf`;

  return {
    fileName,
    mimeType: BANK_SHEET_PDF_MIME_TYPE,
    buffer,
  };
};
