import { PERMISSIONS, type Permission } from '@/config/permissions'
import { routePaths } from '@/config/routePaths'

export type AppRouteSection =
  | 'Overview'
  | 'Administration'
  | 'Master Data'
  | 'Employee Lifecycle'
  | 'Attendance & Leave'
  | 'Payroll Engine'
  | 'Reports & Control'
  | 'System Settings'

export type AppRouteConfigItem = {
  path: string
  title: string
  shortTitle?: string
  description: string
  section: AppRouteSection
  breadcrumbs: string[]
  requiredPermissions?: Permission[]
  status: 'ready' | 'planned'
}

export const appRouteConfig: AppRouteConfigItem[] = [
  {
    path: routePaths.dashboard,
    title: 'Dashboard',
    description:
      'Central landing page for HR, attendance, payroll, report, and audit summaries.',
    section: 'Overview',
    breadcrumbs: ['Dashboard'],
    status: 'ready',
  },
  {
    path: routePaths.users,
    title: 'User Management',
    shortTitle: 'Users',
    description: 'Manage application users, account status, roles, and access scope.',
    section: 'Administration',
    breadcrumbs: ['Administration', 'Users'],
    requiredPermissions: [PERMISSIONS.USER_READ],
    status: 'planned',
  },
  {
    path: routePaths.companies,
    title: 'Company / Concern Setup',
    shortTitle: 'Companies',
    description: 'Maintain CSRM concerns, sister concerns, and company-level filters.',
    section: 'Master Data',
    breadcrumbs: ['Master Data', 'Companies'],
    requiredPermissions: [PERMISSIONS.COMPANY_READ],
    status: 'ready',
  },
  {
    path: routePaths.branches,
    title: 'Branch Setup',
    shortTitle: 'Branches',
    description: 'Maintain branch/location records used by employees and reports.',
    section: 'Master Data',
    breadcrumbs: ['Master Data', 'Branches'],
    requiredPermissions: [PERMISSIONS.BRANCH_READ],
    status: 'ready',
  },
  {
    path: routePaths.majorDepartments,
    title: 'Major Department Setup',
    shortTitle: 'Major Departments',
    description: 'Maintain Office, SMS, ARRM, Accounts, Sales, Scrap Yard, and other groups.',
    section: 'Master Data',
    breadcrumbs: ['Master Data', 'Major Departments'],
    requiredPermissions: [PERMISSIONS.MAJOR_DEPARTMENT_READ],
    status: 'ready',
  },
  {
    path: routePaths.departments,
    title: 'Department / Section Setup',
    shortTitle: 'Departments',
    description: 'Maintain departments, sub-departments, and section-level reporting groups.',
    section: 'Master Data',
    breadcrumbs: ['Master Data', 'Departments'],
    requiredPermissions: [PERMISSIONS.DEPARTMENT_READ],
    status: 'ready',
  },
  {
    path: routePaths.designations,
    title: 'Designation Setup',
    shortTitle: 'Designations',
    description: 'Maintain job titles/designations used in employee profiles and reports.',
    section: 'Master Data',
    breadcrumbs: ['Master Data', 'Designations'],
    requiredPermissions: [PERMISSIONS.DESIGNATION_READ],
    status: 'ready',
  },
  {
    path: routePaths.companyBankAccounts,
    title: 'Company Bank Accounts',
    shortTitle: 'Bank Accounts',
    description: 'Maintain company bank accounts used for salary, bonus, and payment exports.',
    section: 'Master Data',
    breadcrumbs: ['Master Data', 'Company Bank Accounts'],
    requiredPermissions: [PERMISSIONS.COMPANY_BANK_ACCOUNT_READ],
    status: 'ready',
  },
  {
    path: routePaths.employees,
    title: 'Employee Directory',
    shortTitle: 'Employees',
    description: 'Search, filter, create, update, soft-delete, restore, and review employee profile foundation records.',
    section: 'Employee Lifecycle',
    breadcrumbs: ['Employees', 'Directory'],
    requiredPermissions: [PERMISSIONS.EMPLOYEE_READ],
    status: 'ready',
  },
  {
    path: routePaths.employeeBulkImport,
    title: 'Employee Bulk Import',
    shortTitle: 'Bulk Import',
    description: 'Upload employee templates, review validation results, and rollback imports.',
    section: 'Employee Lifecycle',
    breadcrumbs: ['Employees', 'Bulk Import'],
    requiredPermissions: [PERMISSIONS.EMPLOYEE_BULK_IMPORT_READ],
    status: 'planned',
  },
  {
    path: routePaths.employeeMovements,
    title: 'Employee Movement',
    shortTitle: 'Movements',
    description: 'Manage transfer, promotion, salary impact, and effective-date movements.',
    section: 'Employee Lifecycle',
    breadcrumbs: ['Employees', 'Movements'],
    requiredPermissions: [PERMISSIONS.EMPLOYEE_MOVEMENT_READ],
    status: 'planned',
  },
  {
    path: routePaths.attendance,
    title: 'Attendance Register',
    shortTitle: 'Attendance',
    description: 'Review daily attendance, manual corrections, and attendance summaries.',
    section: 'Attendance & Leave',
    breadcrumbs: ['Attendance', 'Register'],
    requiredPermissions: [PERMISSIONS.ATTENDANCE_READ],
    status: 'ready',
  },
  {
    path: routePaths.attendanceImports,
    title: 'Attendance Import',
    shortTitle: 'Imports',
    description: 'Import biometric/punch data, review rejected rows, and track import batches.',
    section: 'Attendance & Leave',
    breadcrumbs: ['Attendance', 'Imports'],
    requiredPermissions: [PERMISSIONS.ATTENDANCE_IMPORT_READ],
    status: 'planned',
  },
  {
    path: routePaths.attendanceFinalizations,
    title: 'Attendance Finalization',
    shortTitle: 'Finalization',
    description: 'Finalize, approve, lock, or unlock attendance before payroll processing.',
    section: 'Attendance & Leave',
    breadcrumbs: ['Attendance', 'Finalization'],
    requiredPermissions: [PERMISSIONS.ATTENDANCE_FINALIZATION_READ],
    status: 'planned',
  },
  {
    path: routePaths.leave,
    title: 'Leave Applications',
    shortTitle: 'Leave',
    description: 'Manage employee leave applications, approvals, and leave status lifecycle.',
    section: 'Attendance & Leave',
    breadcrumbs: ['Leave', 'Applications'],
    requiredPermissions: [PERMISSIONS.LEAVE_READ],
    status: 'ready',
  },
  {
    path: routePaths.leaveBalances,
    title: 'Leave Balances',
    shortTitle: 'Balances',
    description: 'Review opening balances, adjustments, ledgers, and yearly leave balance locks.',
    section: 'Attendance & Leave',
    breadcrumbs: ['Leave', 'Balances'],
    requiredPermissions: [PERMISSIONS.LEAVE_BALANCE_READ],
    status: 'planned',
  },
  {
    path: routePaths.holidays,
    title: 'Holiday Calendar',
    shortTitle: 'Holidays',
    description: 'Maintain holidays used by attendance, leave, and replace-leave calculations.',
    section: 'Attendance & Leave',
    breadcrumbs: ['Leave', 'Holidays'],
    requiredPermissions: [PERMISSIONS.HOLIDAY_READ],
    status: 'planned',
  },
  {
    path: routePaths.payroll,
    title: 'Payroll Run',
    shortTitle: 'Payroll',
    description: 'Process payroll, approve payroll, pay salary, and lock payroll periods.',
    section: 'Payroll Engine',
    breadcrumbs: ['Payroll', 'Run'],
    requiredPermissions: [PERMISSIONS.PAYROLL_READ],
    status: 'ready',
  },
  {
    path: routePaths.salaryStructures,
    title: 'Salary Structure',
    shortTitle: 'Structures',
    description: 'Maintain salary heads, effective dates, and salary structure versions.',
    section: 'Payroll Engine',
    breadcrumbs: ['Salary', 'Structures'],
    requiredPermissions: [PERMISSIONS.SALARY_STRUCTURE_READ],
    status: 'ready',
  },
  {
    path: routePaths.salarySheets,
    title: 'Salary Sheets',
    shortTitle: 'Salary Sheets',
    description: 'Generate, preview, approve, lock, and export monthly salary sheets.',
    section: 'Payroll Engine',
    breadcrumbs: ['Salary', 'Sheets'],
    requiredPermissions: [PERMISSIONS.SALARY_SHEET_READ],
    status: 'ready',
  },
  {
    path: routePaths.salaryStatements,
    title: 'Salary Statements',
    shortTitle: 'Statements',
    description: 'Prepare employee-wise and company-wise salary statements.',
    section: 'Payroll Engine',
    breadcrumbs: ['Salary', 'Statements'],
    requiredPermissions: [PERMISSIONS.SALARY_STATEMENT_READ],
    status: 'ready',
  },
  {
    path: routePaths.salaryPaymentDistributions,
    title: 'Salary Payment Distribution',
    shortTitle: 'Payment Distribution',
    description: 'Prepare bank/cash/mobile salary payment distribution records.',
    section: 'Payroll Engine',
    breadcrumbs: ['Salary', 'Payment Distribution'],
    requiredPermissions: [PERMISSIONS.SALARY_PAYMENT_DISTRIBUTION_READ],
    status: 'ready',
  },

  {
    path: routePaths.legacySalaryImports,
    title: 'Legacy Salary Import',
    shortTitle: 'Legacy Salary',
    description: 'Upload, preview, commit, search, summarize, and export external salary sheets without changing native payroll.',
    section: 'Payroll Engine',
    breadcrumbs: ['Salary', 'Legacy Import'],
    requiredPermissions: [PERMISSIONS.LEGACY_SALARY_IMPORT_READ],
    status: 'ready',
  },
  {
    path: routePaths.timeBills,
    title: 'Time Bill / OT Bill',
    shortTitle: 'Time Bill',
    description: 'Process time bills, OT hours, tiffin, and payable OT statements.',
    section: 'Payroll Engine',
    breadcrumbs: ['Time Bill', 'Bills'],
    requiredPermissions: [PERMISSIONS.TIME_BILL_READ],
    status: 'planned',
  },
  {
    path: routePaths.otStatements,
    title: 'OT Statements',
    shortTitle: 'OT Statements',
    description: 'Review and export overtime statements with approval/lock lifecycle.',
    section: 'Payroll Engine',
    breadcrumbs: ['Time Bill', 'OT Statements'],
    requiredPermissions: [PERMISSIONS.OT_STATEMENT_READ],
    status: 'planned',
  },
  {
    path: routePaths.otPaymentDistributions,
    title: 'OT Payment Distribution',
    shortTitle: 'OT Payments',
    description: 'Prepare overtime payment distribution records for export and payment.',
    section: 'Payroll Engine',
    breadcrumbs: ['Time Bill', 'Payment Distribution'],
    requiredPermissions: [PERMISSIONS.OT_PAYMENT_DISTRIBUTION_READ],
    status: 'planned',
  },
  {
    path: routePaths.bonus,
    title: 'Bonus Sheets',
    shortTitle: 'Bonus',
    description: 'Process bonus sheets, statements, approvals, locks, and payment exports.',
    section: 'Payroll Engine',
    breadcrumbs: ['Bonus', 'Sheets'],
    requiredPermissions: [PERMISSIONS.BONUS_SHEET_READ],
    status: 'planned',
  },
  {
    path: routePaths.bonusStatements,
    title: 'Bonus Statements',
    shortTitle: 'Bonus Statements',
    description: 'Prepare and review bonus statement records by employee and company.',
    section: 'Payroll Engine',
    breadcrumbs: ['Bonus', 'Statements'],
    requiredPermissions: [PERMISSIONS.BONUS_STATEMENT_READ],
    status: 'planned',
  },
  {
    path: routePaths.bonusPaymentDistributions,
    title: 'Bonus Payment Distribution',
    shortTitle: 'Bonus Payments',
    description: 'Prepare bonus payment distribution records for export and payment.',
    section: 'Payroll Engine',
    breadcrumbs: ['Bonus', 'Payment Distribution'],
    requiredPermissions: [PERMISSIONS.BONUS_PAYMENT_DISTRIBUTION_READ],
    status: 'planned',
  },
  {
    path: routePaths.bankSheets,
    title: 'Bank Sheets',
    shortTitle: 'Bank Sheets',
    description: 'Preview bank salary sheets and monthly payroll export routes using backend sub-route patterns.',
    section: 'Payroll Engine',
    breadcrumbs: ['Payroll', 'Bank Sheets'],
    requiredPermissions: [PERMISSIONS.BANK_SHEET_READ],
    status: 'ready',
  },
  {
    path: routePaths.reportCenter,
    title: 'Report Center',
    shortTitle: 'Reports',
    description: 'Catalog, dashboard, readiness, preview, and export entry point for reports.',
    section: 'Reports & Control',
    breadcrumbs: ['Reports', 'Report Center'],
    requiredPermissions: [PERMISSIONS.REPORT_CENTER_READ],
    status: 'ready',
  },
  {
    path: routePaths.salarySummary,
    title: 'Salary Summary',
    shortTitle: 'Salary Summary',
    description: 'Preview and export dedicated backend-calculated salary summary report by company, month, year, and group.',
    section: 'Reports & Control',
    breadcrumbs: ['Reports', 'Salary Summary'],
    requiredPermissions: [PERMISSIONS.SALARY_SUMMARY_READ],
    status: 'ready',
  },
  {
    path: routePaths.reportLayoutStandards,
    title: 'Report Layout Standards',
    shortTitle: 'Layout Standards',
    description: 'Preview standard PDF/Excel/CSV layout rules before report implementation.',
    section: 'Reports & Control',
    breadcrumbs: ['Reports', 'Layout Standards'],
    requiredPermissions: [PERMISSIONS.REPORT_LAYOUT_STANDARD_READ],
    status: 'ready',
  },
  {
    path: routePaths.monthEndControl,
    title: 'Month-End Process Control',
    shortTitle: 'Month-End Control',
    description: 'Review month-end readiness and process-control status before payroll close.',
    section: 'Reports & Control',
    breadcrumbs: ['Reports', 'Month-End Control'],
    requiredPermissions: [PERMISSIONS.MONTH_END_PROCESS_CONTROL_READ],
    status: 'ready',
  },
  {
    path: routePaths.auditLogs,
    title: 'Audit Logs',
    shortTitle: 'Audit Logs',
    description: 'Inspect system audit trail, filters, status changes, sensitive actions, and request metadata.',
    section: 'Reports & Control',
    breadcrumbs: ['Audit', 'Logs'],
    requiredPermissions: [PERMISSIONS.AUDIT_LOG_READ],
    status: 'ready',
  },
  {
    path: routePaths.rbacAudit,
    title: 'RBAC Audit',
    shortTitle: 'RBAC Audit',
    description: 'Review RBAC summary, role matrix, permission coverage, route coverage, and security issues.',
    section: 'Reports & Control',
    breadcrumbs: ['Audit', 'RBAC'],
    requiredPermissions: [PERMISSIONS.RBAC_AUDIT_READ],
    status: 'ready',
  },
  {
    path: routePaths.profile,
    title: 'Profile Settings',
    shortTitle: 'Profile',
    description: 'Future user profile page for personal details, password, and account preferences.',
    section: 'System Settings',
    breadcrumbs: ['Settings', 'Profile'],
    status: 'planned',
  },
  {
    path: routePaths.themeSettings,
    title: 'Theme & Layout Settings',
    shortTitle: 'Theme Settings',
    description: 'Control light/dark/system mode, color preset, density, and layout behavior.',
    section: 'System Settings',
    breadcrumbs: ['Settings', 'Theme'],
    status: 'ready',
  },
]

export const getRouteConfigByPath = (pathname: string) => {
  return (
    appRouteConfig.find((route) => route.path === pathname) ??
    appRouteConfig.find(
      (route) => route.path !== routePaths.root && pathname.startsWith(route.path),
    )
  )
}
