import { z } from "zod";
import { LEAVE_TYPES } from "../leave/leave.constant";

const objectIdSchema = (fieldName: string) =>
  z
    .string()
    .trim()
    .regex(/^[0-9a-fA-F]{24}$/, `Invalid ${fieldName}`);

const yearSchema = z
  .number()
  .int()
  .min(2000, "Year must be greater than or equal to 2000")
  .max(2100, "Year must be less than or equal to 2100");

const yearStringSchema = z
  .string()
  .trim()
  .regex(/^\d{4}$/, "Year must follow YYYY format")
  .optional();

const dateStringSchema = z
  .string()
  .trim()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "Date must follow YYYY-MM-DD format");

const booleanStringSchema = z.enum(["true", "false"]).optional();
const leaveTypeSchema = z.enum(LEAVE_TYPES).optional();

const actionBodySchema = z
  .object({
    note: z.string().trim().max(500).optional(),
    actionBy: objectIdSchema("action by user id").optional(),
  })
  .strict()
  .optional();

const queryFilterSchema = z
  .object({
    year: yearStringSchema,
    company: objectIdSchema("company id").optional(),
    majorDepartment: objectIdSchema("major department id").optional(),
    department: objectIdSchema("department id").optional(),
    branch: objectIdSchema("branch id").optional(),
    employee: objectIdSchema("employee id").optional(),
    leaveType: leaveTypeSchema,
    status: z.enum(["generated", "locked"]).optional(),
    isLocked: booleanStringSchema,
  })
  .strict();

const generateLeaveBalanceValidationSchema = z.object({
  body: z
    .object({
      year: yearSchema,
      company: objectIdSchema("company id"),
      majorDepartment: objectIdSchema("major department id").optional(),
      department: objectIdSchema("department id").optional(),
      branch: objectIdSchema("branch id").optional(),
      employee: objectIdSchema("employee id").optional(),
      overwrite: z.boolean().optional(),
      generatedBy: objectIdSchema("generated by user id").optional(),
      remarks: z.string().trim().max(500).optional(),
    })
    .strict(),
});

const leaveBalanceQueryValidationSchema = z.object({
  query: queryFilterSchema,
});

const leaveBalanceSummaryQueryValidationSchema = z.object({
  query: queryFilterSchema.omit({ leaveType: true, status: true, isLocked: true }),
});

const leaveBalanceIdParamValidationSchema = z.object({
  params: z.object({
    id: objectIdSchema("leave balance id"),
  }),
});

const leaveBalanceActionValidationSchema = z.object({
  params: z.object({
    id: objectIdSchema("leave balance id"),
  }),
  body: actionBodySchema,
});

const leaveBalanceOpeningBalanceValidationSchema = z.object({
  params: z.object({
    id: objectIdSchema("leave balance id"),
  }),
  body: z
    .object({
      openingBalance: z
        .number()
        .min(0, "Opening balance cannot be negative")
        .max(365, "Opening balance is unusually high"),
      reason: z.string().trim().min(3).max(500),
      effectiveDate: dateStringSchema.optional(),
      note: z.string().trim().max(500).optional(),
      actionBy: objectIdSchema("action by user id").optional(),
    })
    .strict(),
});

const leaveBalanceAdjustmentValidationSchema = z.object({
  params: z.object({
    id: objectIdSchema("leave balance id"),
  }),
  body: z
    .object({
      adjustmentType: z.enum(["credit", "debit"]),
      days: z
        .number()
        .positive("Adjustment days must be greater than zero")
        .max(365, "Adjustment days is unusually high"),
      reason: z.string().trim().min(3).max(500),
      effectiveDate: dateStringSchema.optional(),
      note: z.string().trim().max(500).optional(),
      actionBy: objectIdSchema("action by user id").optional(),
    })
    .strict(),
});

const leaveBalanceExportQueryValidationSchema = z.object({
  query: queryFilterSchema,
});

const leaveBalanceLedgerQueryValidationSchema = z.object({
  query: z
    .object({
      year: yearStringSchema,
      company: objectIdSchema("company id").optional(),
      employee: objectIdSchema("employee id"),
      leaveType: leaveTypeSchema,
    })
    .strict(),
});

const leaveBalanceBulkActionValidationSchema = z.object({
  body: z
    .object({
      year: yearSchema,
      company: objectIdSchema("company id").optional(),
      majorDepartment: objectIdSchema("major department id").optional(),
      department: objectIdSchema("department id").optional(),
      branch: objectIdSchema("branch id").optional(),
      employee: objectIdSchema("employee id").optional(),
      note: z.string().trim().max(500).optional(),
      actionBy: objectIdSchema("action by user id").optional(),
      strict: z.boolean().optional(),
    })
    .strict(),
});

export const LeaveBalanceValidations = {
  generateLeaveBalanceValidationSchema,
  leaveBalanceQueryValidationSchema,
  leaveBalanceSummaryQueryValidationSchema,
  leaveBalanceIdParamValidationSchema,
  leaveBalanceActionValidationSchema,
  leaveBalanceOpeningBalanceValidationSchema,
  leaveBalanceAdjustmentValidationSchema,
  leaveBalanceExportQueryValidationSchema,
  leaveBalanceLedgerQueryValidationSchema,
  leaveBalanceBulkActionValidationSchema,
};
