export const generatePayslipPDF = (doc: any, data: any) => {
  // Title
  doc.fontSize(20).text("Employee Payslip", { align: "center" });

  doc.moveDown();

  // Employee Information
  doc.fontSize(12).text(`Employee Name: ${data?.employee?.fullName || ""}`);
  doc.text(`Employee Code: ${data?.employee?.employeeCode || ""}`);
  doc.text(`Department: ${data?.employee?.department || ""}`);
  doc.text(`Designation: ${data?.employee?.designation || ""}`);
  doc.text(`Branch: ${data?.employee?.branch || ""}`);

  doc.moveDown();

  // Payroll Information
  doc.text(`Payroll Month: ${data?.monthLabel || ""}`);

  doc.moveDown();

  doc.text(`Gross Salary: ${data?.payroll?.grossSalary ?? 0}`);
  doc.text(`Fixed Deduction: ${data?.payroll?.fixedDeduction ?? 0}`);
  doc.text(`Attendance Deduction: ${data?.payroll?.attendanceDeduction ?? 0}`);
  doc.text(`Total Deduction: ${data?.payroll?.totalDeduction ?? 0}`);
  doc.text(`Net Salary: ${data?.payroll?.netSalary ?? 0}`);
  doc.text(`Payable Salary: ${data?.payroll?.payableSalary ?? 0}`);

  doc.moveDown();

  doc.text(`Status: ${data?.payroll?.status || ""}`);
  doc.text(`Remarks: ${data?.payroll?.remarks || ""}`);

  doc.moveDown(2);

  doc.text("Generated by CSRM Payroll System", {
    align: "center",
  });
};
